### ISSUE TITLE
Way to update a list of elements?

### ISSUE THREAD

**Issue by paulcpederson** [bevacqua/diferente#1]
Let's say I have an unordered list like this:

```
<ul id="list1"></ul>
```

and I generate a string containing all the list items and diff them:

```
var listItems = '<li>1</li><li>2</li>'
var list1 = document.getElementById('list1')

diferente(list1, listItems)
```

I get the a list with only the last item (`<li>2</li>`). Is there a way to get all the list items added without wrapping them in a separate dom node?

**Comment by bevacqua** [comment]
Nope, you'll have to generate the list as well

**Comment by paulcpederson** [comment]
@bevacqua thanks
